### ISSUE TITLE
Add TypeScript Typing definations

### ISSUE THREAD

**Issue by zixia** [nodejs-tensorflow/nodejs-tensorflow#6]
Hi!

I'm so glad to see this tensorflow nodejs implementation!

I'd like to suggest to add Type Definition to this library, or one step deeper, I'd like to suggest to write this project in TypeScript instead of JS, because the type checker will help the code improve quality a lot.

TypeScript is used by Angular by default, and VSCode has very good static check and IntelliSense support for it. 

Please consider. If we decide to use TypeScript, I'd be very happy to contribute this part because I'm a TS fan. Thanks!

**Comment by djimoh5** [comment]
I second this, and would also be happy to contribute if the library was written in Typescript. At the moment, I am currently working on my own neural net implementation in Typescript, that employs node C++ add-ons to enhance the performance of all matrix operations. I've been careful to build with TensorFlow in mind, in hopes of one day being able to seamlessly flip the net back and forth between my implementation and TensorFlow's. Excited that someone is kicking off this project, but would also highly advise that this be done in Typescript. If so, i'm waiting and ready to contribute!

**Comment by JIoJIaJIu** [comment]
Hello @zixia and @djimoh5 
Thanks a lot for your suggestions, unfortunately, I am not familiar with `TypeScript` so at this point I cannot be sure that switching on `TypeScript` implementation is the right way. But I really agree to add interface declarations - looks like it's what you mean @zixia when told about `type definitions`. In progress we can discuss again an opportunity about switching on `TypeScript`, for example, if library will be easily pluggable few components can be implemented on `TypeScript`. So I mark this task as `contributers-welcome`

**Comment by zixia** [comment]
Hello @JIoJIaJIu 

Here's my favorite TypeScript introduction video: [What's new in TypeScript?](https://channel9.msdn.com/Events/Build/2017/B8088), it worth to have a look. 

After we wrote in TypeScript, we will get all benefits from it.

If you'd like to see what `nodejs-tensorflow` will look like after we switched on TypeScript, I'd like to send a PR to show you a demo. 

Do you want me to make the demo?

**Comment by JIoJIaJIu** [comment]
Thank @zixia, will look at this weekend and tell more what I think. At this time I think that switching project on  `TypeScript` is not the goal. I mean that there are a lot of work in other spaces, but it will be great if you start to implement interface declarations as you described above

**Comment by JIoJIaJIu** [comment]
@zixia @djimoh5 I watched the video and think that `TypeScript` is what is needed for this project. I created [the task](https://github.com/nodejs-tensorflow/nodejs-tensorflow/issues/8) that would like to finish by my own for facing with it in the real world. Thanks a lot, fill free to share your opinions, suggestions and code)

**Comment by zixia** [comment]
@JIoJIaJIu awesome! 

Please let me know if you need any help, and I would like to contribute to this project as you needed. :D

**Comment by JIoJIaJIu** [comment]
I created [issue](https://github.com/nodejs-tensorflow/nodejs-tensorflow/issues/9) based on it, you can help me with it

**Comment by djimoh5** [comment]
Excellent, this is wonderful to hear. I've been writing Typescript for a few years  now so please let me know what I can help with.

**Comment by JIoJIaJIu** [comment]
@djimoh5  I can suggest joining slack as I described in `README.md`
There is [such task](https://github.com/nodejs-tensorflow/nodejs-tensorflow/issues/1), I think it would be great to integrate any doc tool for parsing `ts` file
